INSERT INTO expense (category, amount, date, supplier_id, store_id, note) VALUES
    ('Inventory', 450.00, NOW() - INTERVAL '1 day', 1, 1, 'Coffee beans bulk order'),
    ('Inventory', 180.00, NOW() - INTERVAL '1 day', 2, 1, 'Milk and cream supply'),
    ('Utilities', 120.00, NOW() - INTERVAL '2 days', NULL, 1, 'Electricity bill'),
    ('Inventory', 200.00, NOW() - INTERVAL '2 days', 3, 1, 'Pastry delivery'),
    ('Equipment', 250.00, NOW() - INTERVAL '3 days', NULL, 1, 'Espresso machine maintenance'),
    ('Inventory', 420.00, NOW() - INTERVAL '4 days', 1, 2, 'Coffee beans order - Airport location'),
    ('Inventory', 150.00, NOW() - INTERVAL '4 days', 2, 2, 'Dairy products - Airport'),
    ('Utilities', 180.00, NOW() - INTERVAL '5 days', NULL, 2, 'Electricity and water - Airport'),
    ('Inventory', 190.00, NOW() - INTERVAL '5 days', 3, 2, 'Pastries for Airport terminal'),
    ('Equipment', 300.00, NOW() - INTERVAL '6 days', NULL, 2, 'Grinder replacement parts'),
    ('Inventory', 380.00, NOW() - INTERVAL '7 days', 1, 3, 'Coffee beans - University location'),
    ('Inventory', 160.00, NOW() - INTERVAL '7 days', 2, 3, 'Milk supply - University'),
    ('Utilities', 140.00, NOW() - INTERVAL '8 days', NULL, 3, 'Campus utilities'),
    ('Inventory', 210.00, NOW() - INTERVAL '8 days', 3, 3, 'Bakery items for campus'),
    ('Equipment', 220.00, NOW() - INTERVAL '9 days', NULL, 3, 'Coffee maker repair'),
    ('Inventory', 470.00, NOW() - INTERVAL '10 days', 1, 1, 'Premium coffee beans order'),
    ('Inventory', 175.00, NOW() - INTERVAL '10 days', 2, 1, 'Organic milk supply'),
    ('Utilities', 135.00, NOW() - INTERVAL '11 days', NULL, 1, 'Monthly utilities'),
    ('Inventory', 195.00, NOW() - INTERVAL '11 days', 3, 1, 'Fresh pastries delivery'),
    ('Marketing', 150.00, NOW() - INTERVAL '12 days', NULL, 1, 'Local advertising'),
    ('Inventory', 440.00, NOW() - INTERVAL '13 days', 1, 2, 'Coffee inventory restock'),
    ('Inventory', 170.00, NOW() - INTERVAL '13 days', 2, 2, 'Dairy restock - Airport'),
    ('Utilities', 165.00, NOW() - INTERVAL '14 days', NULL, 2, 'Airport location utilities'),
    ('Inventory', 205.00, NOW() - INTERVAL '14 days', 3, 2, 'Pastry restock'),
    ('Marketing', 200.00, NOW() - INTERVAL '15 days', NULL, 2, 'Airport terminal advertising'),
    ('Inventory', 390.00, NOW() - INTERVAL '16 days', 1, 3, 'Coffee beans - University'),
    ('Inventory', 155.00, NOW() - INTERVAL '16 days', 2, 3, 'Milk supply - Campus'),
    ('Utilities', 145.00, NOW() - INTERVAL '17 days', NULL, 3, 'Campus utilities'),
    ('Inventory', 185.00, NOW() - INTERVAL '17 days', 3, 3, 'Bakery items'),
    ('Marketing', 120.00, NOW() - INTERVAL '18 days', NULL, 3, 'Student promotion materials');

INSERT INTO supplier (name, contact, ingredient_type) VALUES
    ('Premium Coffee Co', 'orders@premiumcoffee.com', 'Coffee Beans'),
    ('Local Dairy Farm', 'sales@localdairy.com', 'Milk & Cream'),
    ('Artisan Bakery', 'info@artisanbakery.com', 'Pastries'),
    ('Bulk Beans Wholesale', 'contact@bulkbeans.com', 'Coffee Beans'),
    ('Fresh Milk Direct', 'orders@freshmilk.com', 'Milk & Cream');

INSERT INTO supplierprice (supplier_id, product_id, price, effective_date) VALUES
    (1, 1, 0.48, NOW() - INTERVAL '30 days'),
    (1, 2, 1.10, NOW() - INTERVAL '30 days'),
    (1, 3, 1.15, NOW() - INTERVAL '30 days'),
    (1, 4, 0.95, NOW() - INTERVAL '30 days'),
    (1, 5, 1.40, NOW() - INTERVAL '30 days'),
    (4, 1, 0.45, NOW() - INTERVAL '20 days'),
    (4, 2, 1.05, NOW() - INTERVAL '20 days'),
    (4, 3, 1.12, NOW() - INTERVAL '20 days'),
    (4, 4, 0.92, NOW() - INTERVAL '20 days'),
    (4, 5, 1.35, NOW() - INTERVAL '20 days'),
    (2, 2, 1.25, NOW() - INTERVAL '30 days'),
    (2, 3, 1.28, NOW() - INTERVAL '30 days'),
    (2, 5, 1.55, NOW() - INTERVAL '30 days'),
    (5, 2, 1.20, NOW() - INTERVAL '15 days'),
    (5, 3, 1.25, NOW() - INTERVAL '15 days'),
    (5, 5, 1.50, NOW() - INTERVAL '15 days'),
    (3, 6, 0.78, NOW() - INTERVAL '30 days'),
    (3, 7, 0.88, NOW() - INTERVAL '30 days'),
    (3, 8, 0.58, NOW() - INTERVAL '30 days'),
    (6, 6, 0.75, NOW() - INTERVAL '10 days'),
    (6, 7, 0.85, NOW() - INTERVAL '10 days'),
    (6, 8, 0.55, NOW() - INTERVAL '10 days'),
    (1, 1, 0.50, NOW() - INTERVAL '5 days'),
    (1, 2, 1.12, NOW() - INTERVAL '5 days'),
    (4, 1, 0.47, NOW() - INTERVAL '3 days'),
    (4, 2, 1.08, NOW() - INTERVAL '3 days'),
    (2, 2, 1.27, NOW() - INTERVAL '7 days'),
    (5, 2, 1.22, NOW() - INTERVAL '2 days'),
    (3, 6, 0.80, NOW() - INTERVAL '8 days'),
    (6, 6, 0.77, NOW() - INTERVAL '4 days');

